# Changes here will be overwritten by Copier
_commit: v0.4.1
_src_path: https://github.com/linkml/linkml-project-copier
add_example: true
copyright_year: '2025'
email: smoxon@lbl.gov
full_name: Sierra Moxon
gh_action_docs_preview: false
gh_action_pypi: true
github_org: EHS-Data-Standards
license: MIT
project_description: This is the project description.
project_name: outcomes-working-group
project_slug: outcomes_working_group

